name: teste execução automatica

on:
  schedule:
    - cron: '0 22 * * *'

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Executar script
        run: python seu_script.py
